question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Water boils at 100°C at sea level.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "The Eiffel Tower is located in Berlin.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain above sea level.", "answer": "True"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Humans and dinosaurs lived at the same time.", "answer": "False"},
    {"text": "The currency of Japan is the Yen.", "answer": "True"},
    {"text": "The human heart has five chambers.", "answer": "False"},
    {"text": "A group of lions is called a pride.", "answer": "True"},
    {"text": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"text": "The moon produces its own light.", "answer": "False"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "Goldfish have a memory span of only three seconds.", "answer": "False"},
    {"text": "The human skeleton contains 206 bones.", "answer": "True"},
    {"text": "The Statue of Liberty was a gift from France.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The Earth is the center of the Solar System.", "answer": "False"},
    {"text": "A leap year occurs every four years.", "answer": "True"},
    {"text": "The Sahara is the largest desert in the world.", "answer": "False"},
    {"text": "Spiders have six legs.", "answer": "False"},
    {"text": "The human brain stops developing after age 10.", "answer": "False"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "New York is the capital of the United States.", "answer": "False"},
    {"text": "The blue whale is the largest animal ever known to exist.", "answer": "True"},
    {"text": "The square root of 64 is 8.", "answer": "True"},
    {"text": "The human body has 32 teeth in a full adult set.", "answer": "True"},
    {"text": "Cheetahs are the fastest land animals.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "The Earth revolves around the Sun.", "answer": "True"},
    {"text": "The Atlantic Ocean is larger than the Pacific Ocean.", "answer": "False"},
    {"text": "Dolphins are fish.", "answer": "False"},
    {"text": "The longest bone in the human body is the femur.", "answer": "True"},
    {"text": "Mercury is the hottest planet in the Solar System.", "answer": "False"},
    {"text": "The speed of sound is approximately 343 m/s in air.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "The capital of Italy is Rome.", "answer": "True"},
    {"text": "Humans have five senses.", "answer": "False"},
    {"text": "Albert Einstein won a Nobel Prize in Physics.", "answer": "True"},
    {"text": "The sun is a planet.", "answer": "False"},
    {"text": "The shortest war in history lasted less than an hour.", "answer": "True"},
    {"text": "Koalas are bears.", "answer": "False"},
    {"text": "A heptagon has seven sides.", "answer": "True"},
    {"text": "The largest continent is Asia.", "answer": "True"},
    {"text": "The human body contains more bacterial cells than human cells.", "answer": "False"},
    {"text": "The currency of the United Kingdom is the Pound Sterling.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "There are 25 hours in a day.", "answer": "False"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "The Earth has two moons.", "answer": "False"},
    {"text": "Jupiter is the largest planet in the Solar System.", "answer": "True"},
    {"text": "The Titanic sank in 1912.", "answer": "True"},
    {"text": "An adult human has 300 bones.", "answer": "False"},
    {"text": "The longest English word has 189,819 letters.", "answer": "True"},
    {"text": "The capital of India is Mumbai.", "answer": "False"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Antarctica is the coldest continent.", "answer": "True"},
    {"text": "The Sun rises in the west.", "answer": "False"},
    {"text": "The hummingbird is the only bird that can fly backwards.", "answer": "True"},
    {"text": "A kilogram is heavier than a pound.", "answer": "True"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "Mice are larger than rats.", "answer": "False"},
    {"text": "A bolt of lightning is hotter than the surface of the Sun.", "answer": "True"},
    {"text": "The human eye can distinguish millions of colors.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The Earth is perfectly round.", "answer": "False"},
    {"text": "The first man on the Moon was Neil Armstrong.", "answer": "True"},
    {"text": "An octagon has eight sides.", "answer": "True"},
    {"text": "The capital of Russia is St. Petersburg.", "answer": "False"},
    {"text": "A day on Mars is longer than a day on Earth.", "answer": "True"},
    {"text": "There are seven continents on Earth.", "answer": "True"},
    {"text": "The chemical symbol for water is H2O.", "answer": "True"},
    {"text": "The human body has three kidneys.", "answer": "False"},
    {"text": "The world's largest rainforest is the Amazon Rainforest.", "answer": "True"},
    {"text": "The Earth is approximately 4.5 billion years old.", "answer": "True"}
]